root = "."
tmp_dir = "tmp/controller-service"

[build]
cmd = "go build -o ./tmp/controller-service/server ./apps/controller-service/cmd/server"
bin = "./tmp/controller-service/server"
include_dir = ["apps", "libs"]
exclude_dir = ["tmp", ".git", "node_modules", "terraform"]
delay = 1000
