apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-webxr.yaml
  - controller-service.yaml
  - master-service.yaml
  - slave-service.yaml
  - cloudflared.yaml
  - nginx-proxy.yaml