---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      auth:
        workloadIdentity:
          clusterLocation: asia-northeast1
          clusterName: hackz-megalo-cluster
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflared-secret
  data:
    - secretKey: CLOUDFLARED_TOKEN
      remoteRef:
        key: cloudflared-token-secret
