apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/frontend-webxr.yaml
  - ../../base/nginx-proxy.yaml
  - ../../base/cloudflared.yaml
  - ../production/external-secret.yaml
