$patch: delete
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-service
---
$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: controller-service-svc
---
$patch: delete
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-service
---
$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: master-service-svc
---
$patch: delete
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave-service
---
$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: slave-service-svc
