---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflared-secret-sync
  namespace: default
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cloudflared-secret-provider
  namespace: default
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/hackz-megalo-cup/secrets/cloudflared-token-secret/versions/latest"
        path: "cloudflared-token"
      - resourceName: "projects/hackz-megalo-cup/secrets/cloudflare-access-team-domain-secret/versions/latest"
        path: "cloudflare-access-team-domain"
      - resourceName: "projects/hackz-megalo-cup/secrets/cloudflare-access-audience-secret/versions/latest"
        path: "cloudflare-access-audience"
---
apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: cloudflared-secret
  namespace: default
spec:
  serviceAccountName: cloudflared-secret-sync
  secretProviderClassName: cloudflared-secret-provider
  secretObject:
    type: Opaque
    data:
      - sourcePath: "cloudflared-token"
        targetKey: "CLOUDFLARED_TOKEN"
      - sourcePath: "cloudflare-access-team-domain"
        targetKey: "CLOUDFLARE_ACCESS_TEAM_DOMAIN"
      - sourcePath: "cloudflare-access-audience"
        targetKey: "CLOUDFLARE_ACCESS_AUDIENCE"
