---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: hackz-megalo-cup
      auth:
        workloadIdentity:
          clusterLocation: asia-northeast1
          clusterName: hackz-megalo-cluster
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflared-secret # Matches the envFrom secretRef in Deployment
  data:
    - secretKey: CLOUDFLARED_TOKEN # Key inside K8s Secret
      remoteRef:
        key: cloudflared-token-secret # Name of the Secret in GCP Secret Manager
