apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - external-secret.yaml

patches:
  - target:
      kind: Deployment
      name: master-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1
        value:
          name: MASTER_REDIS_ADDR
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: REDIS_ADDR
  - target:
      kind: Deployment
      name: controller-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1
        value:
          name: CONTROLLER_REDIS_ADDR
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: REDIS_ADDR
